name: gaze-stars
description: Generate starred list of yourself.
author: zhuozhiyongde (zhuozhiyongde@126.com), Frestein (fretein@tuta.io)
branding:
  icon: star
  color: yellow
inputs:
  github-username:
    description: GitHub username to generate starred list for
    required: true
  git-message:
    description: Commit message
    default: "chore(updates): updated entries in files"
  sort-by:
    description: Sort by (stars, updated)
    default: stars
  style:
    description: Style of README generation (table, list)
    default: table
  template-path:
    description: Path to custom README template
    default: template/template.md
  output-path:
    description: Output file path
    default: README.md
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        git clone https://github.com/Frestein/gaze-stars.git
        cd gaze-stars
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Run Stargazer
      run: |
        python gaze-stars/Stargazer.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ inputs.github-username }}
        TEMPLATE_PATH: ${{ inputs.template-path }}
        OUTPUT_PATH: ${{ inputs.output-path }}
        SORT_BY: ${{ inputs.sort-by }}
        STYLE: ${{ inputs.style }}
    - name: Commit and push changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add ${{ inputs.output-path }}
        if ! git diff-index --quiet HEAD --; then
          git commit -m "${{ inputs.git-message }}"
          git push
        else
          echo "No changes to commit."
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
